snappmarket/treasury-communicator

src/Treasury/Communicator.php
src/Treasury/Dto/OrderUpdateDto.php

Provide the needs to log updates in order's delivery fee.

add method to store change in order's delivery fee

---

src/Treasury/Communicator.php
src/Treasury/Dto/OrderPayDto.php

* provide a process to store order payment

provide a process to store order payment

---

src/Treasury/Communicator.php
src/Treasury/Dto/OrderCancelCreditReservationDto.php
src/Treasury/Dto/OrderReserveCreditDto.php

* provide methods for credit reservation

provide methods for credit reservation

---

src/Treasury/Communicator.php

* add security token to requests' header
* fix the process for reading the content of the reservation endpoints

add security token to requests' header

---

src/Treasury/Communicator.php
src/Treasury/Dto/OrderCashBackDto.php

* add method for order cash back

add method for order cash back

---

src/Treasury/Communicator.php
src/Treasury/Dto/CreditPayBackDto.php

Added payback request.

---

composer.json

* add caret to the version specified for the php rest communicator package

add caret to parent package versoin

---

src/Treasury/Communicator.php

* fix the method for store order's payment

fix the method for store order's payment

---

src/Treasury/Communicator.php

* change `post` methods to `request`

change `post` methods to `request`

---

src/Treasury/Communicator.php
src/Treasury/Dto/CreditUpdateDto.php
src/Treasury/Dto/TransactionListDto.php

add new `description` field to `Transaction` DTOs.

feat: add new description field in transaction

---

src/Treasury/Dto/PaymentInfoUpdateDto.php

fixed the bug where static:: was used instead of self::

---

src/Treasury/Communicator.php

fixed a typo

---

src/Treasury/Communicator.php
src/Treasury/Dto/OrderRestoreDto.php

* add method to call order restore endpoint of treasury

added method to request order restore

---

src/Treasury/Communicator.php
src/Treasury/Dto/OrderRestorePossibilityDto.php

* Adds new method for calling treasury order restore check possibility API

A new API has been added to check the order restore possibility

---

src/Treasury/Communicator.php
src/Treasury/Dto/CreditUpdateDto.php

* adding new property to user credit updates method

feat: adding references id to credit updates request

---

src/Treasury/Communicator.php
src/Treasury/Dto/OrderReturnDto.php
src/Treasury/Exception/TreasuryInternalServerErrorException.php
src/Treasury/Exception/TreasuryUnprocessableEntityException.php

create a new endpoint for add returning order transactions

add new api for order returning transactions

---

src/Treasury/Communicator.php
src/Treasury/Dto/OrderRevertSnappCreditDto.php

Add a new method to call treasury to store a revert transaction for SnappPay.

add storeOrderRevertForSnappPay method

---

src/Treasury/Communicator.php

SP-4728 - fix already refunded response

---

src/Treasury/Communicator.php

SP-4713 - fix already refunded response

---

src/Treasury/Communicator.php
src/Treasury/Dto/ReturnCancelAmountToSnappCredit.php

feature add return cancel amount method

---

src/Treasury/Communicator.php
src/Treasury/Dto/AlreadyRefundedAmountDto.php
src/Treasury/Dto/PaidByGatewayDto.php

Two endpoint added for SnappPay requests:
getAlreadyRefundedAmount
getPaidByGateway

SP-8464/fix/add two endpoint to treasury
